apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-canary
  labels:
    app: demo-canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-canary
  template:
    metadata:
      labels:
        app: demo-canary
    spec:
      containers:
      - name: demo-canary
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 60
---
apiVersion: v1
kind: Service
metadata:
  name: demo-canary
  labels:
    app: demo
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: demo-canary
  type: NodePort

